export const QUOTES = [
  { text: "Play iterated games. All the returns in life, whether in wealth, relationships, or knowledge, come from compound interest.", author: "Naval Ravikant" },
  { text: "Seek wealth, not money or status. Wealth is having assets that earn while you sleep.", author: "Naval Ravikant" },
  { text: "You get rewarded for unique knowledge, not for effort. Effort is required to create unique knowledge.", author: "Naval Ravikant" },
  { text: "Learn to sell. Learn to build. If you can do both, you will be unstoppable.", author: "Naval Ravikant" },
  { text: "The closer you want to get to me, the better your values have to be.", author: "Naval Ravikant" },
  { text: "You make your own luck if you stay at it long enough.", author: "Naval Ravikant" },
  { text: "A fit body, a calm mind, a house full of love. These things cannot be bought—they must be earned.", author: "Naval Ravikant" },
  { text: "You do not rise to the level of your goals. You fall to the level of your systems.", author: "James Clear" },
  { text: "Every action you take is a vote for the type of person you wish to become.", author: "James Clear" },
  { text: "Habits are the compound interest of self-improvement.", author: "James Clear" },
  { text: "Rome wasn't built in a day, but they were laying bricks every hour.", author: "James Clear" },
  { text: "Success is the product of daily habits—not once-in-a-lifetime transformations.", author: "James Clear" },
  { text: "Some people want it to happen, some wish it would happen, others make it happen.", author: "Michael Jordan" },
  { text: "If you want to be successful, find out what the price is and then pay it.", author: "Scott Adams" },
  { text: "Discipline equals freedom.", author: "Jocko Willink" },
  { text: "Don't stop when you are tired. Stop when you are done.", author: "David Goggins" },
  { text: "I have missed more than 9,000 shots in my career. I have lost almost 300 games. 26 times, I have been trusted to take the game winning shot and missed. I have failed over and over and over again in my life. And that is why I succeed.", author: "Michael Jordan" },
  { text: "I could either watch it happen or be a part of it.", author: "Elon Musk" },
  { text: "When something is important enough, you do it even if the odds are not in your favor.", author: "Elon Musk" },
  { text: "If you get up in the morning and think the future is going to be better, it is a bright day. Otherwise, it's not.", author: "Elon Musk" },
  { text: "Constantly think about how you could be doing things better and questioning yourself.", author: "Elon Musk" },
  { text: "Great companies are built on great products.", author: "Elon Musk" },
  { text: "If you don't find a way to make money while you sleep, you will work until you die.", author: "Warren Buffett" },
  { text: "Be fearful when others are greedy, and greedy when others are fearful.", author: "Warren Buffett" },
  { text: "The most important investment you can make is in yourself.", author: "Warren Buffett" },
  { text: "Someone's sitting in the shade today because someone planted a tree a long time ago.", author: "Warren Buffett" },
  { text: "The biggest risk is not taking any risk... In a world that is changing really quickly, the only strategy that is guaranteed to fail is not taking risks.", author: "Mark Zuckerberg" },
  { text: "Winners never quit and quitters never win.", author: "Vince Lombardi" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.", author: "Colin Powell" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
  { text: "The secret to wealth is simple: Find a way to do more for others than anyone else does.", author: "Tony Robbins" },
  { text: "Setting goals is the first step in turning the invisible into the visible.", author: "Tony Robbins" },
  { text: "It’s not what we do once in a while that shapes our lives, but what we do consistently.", author: "Tony Robbins" },
  { text: "Success in life is the result of good judgment. Good judgment is usually the result of experience. Experience is usually the result of bad judgment.", author: "Tony Robbins" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "Go as far as you can see; when you get there, you'll be able to see further.", author: "Thomas Carlyle" },
  { text: "I never dreamt of success. I worked for it.", author: "Estée Lauder" },
  { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
  { text: "Try not to become a man of success. Rather become a man of value.", author: "Albert Einstein" },
  { text: "Don't let the fear of losing be greater than the excitement of winning.", author: "Robert Kiyosaki" },
  { text: "It’s not how much money you make, but how much money you keep, how hard it works for you, and how many generations you keep it for.", author: "Robert Kiyosaki" },
  { text: "Wealth is the ability to fully experience life.", author: "Henry David Thoreau" },
  { text: "Money usually attracts, not the people who pray for it, but the people who provide value.", author: "Anonymous" },
  { text: "Formal education will make you a living; self-education will make you a fortune.", author: "Jim Rohn" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "Income seldom exceeds personal development.", author: "Jim Rohn" },
  { text: "Success is nothing more than a few simple disciplines, practiced every day.", author: "Jim Rohn" },
  { text: "Don't wish it was easier, wish you were better. Don't wish for less problems, wish for more skills.", author: "Jim Rohn" },
  { text: "If you really want to do something, you'll find a way. If you don't, you'll find an excuse.", author: "Jim Rohn" },
  { text: "You must suffer one of two things: the pain of discipline or the pain of regret.", author: "Jim Rohn" },
  { text: "To earn more, you must learn more.", author: "Brian Tracy" },
  { text: "Successful people are always looking for opportunities to help others. Unsuccessful people are always asking, 'What's in it for me?'", author: "Brian Tracy" },
  { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
  { text: "Long-term consistency trumps short-term intensity.", author: "Bruce Lee" },
  { text: "Empty your mind, be formless. Shapeless, like water. If you put water into a cup, it becomes the cup.", author: "Bruce Lee" },
  { text: "There is only one winning strategy. It is to carefully define the target market and direct a superior offering to that target market.", author: "Philip Kotler" },
  { text: "Execution is the multiplier of your idea.", author: "Derek Sivers" },
  { text: "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", author: "Stephen King" },
  { text: "Talent is cheaper than table salt. What separates the talented individual from the successful one is a lot of hard work.", author: "Stephen King" },
  { text: "If you don't value your time, neither will others.", author: "Kim Garst" },
  { text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
  { text: "Your income is determined by how many people you serve and how well you serve them.", author: "Bob Burg" },
  { text: "Focus entirely on what is in your control—your mind and your actions. Let everything else unfold as it will.", author: "Marcus Aurelius" },
  { text: "Waste no more time arguing what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus" },
  { text: "He who has a why to live for can bear almost any how.", author: "Friedrich Nietzsche" },
  { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
  { text: "No man has the right to be an amateur in the matter of physical training. It is a shame for a man to grow old without seeing the beauty and strength of which his body is capable.", author: "Socrates" },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
  { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
  { text: "It is not the man who has too little, but the man who craves more, that is poor.", author: "Seneca" },
  { text: "If you don't build your dream, someone else will hire you to help them build theirs.", author: "Dhirubhai Ambani" },
  { text: "Work like there is someone working 24 hours a day to take it away from you.", author: "Mark Cuban" },
  { text: "Sweat equity is the most valuable equity there is.", author: "Mark Cuban" },
  { text: "The man who does more than he is paid for will soon be paid for more than he does.", author: "Napoleon Hill" },
  { text: "Whatever the mind of man can conceive and believe, it can achieve.", author: "Napoleon Hill" },
  { text: "Patience, persistence and perspiration make an unbeatable combination for success.", author: "Napoleon Hill" },
  { text: "Do not wait; the time will never be 'just right.' Start where you stand.", author: "Napoleon Hill" },
  { text: "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.", author: "Dale Carnegie" },
  { text: "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.", author: "Charles Darwin" },
  { text: "I attribute my success to this: I never gave or took any excuse.", author: "Florence Nightingale" },
  { text: "Vision without execution is just hallucination.", author: "Henry Ford" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "Great things are not done by impulse, but by a series of small things brought together.", author: "Vincent Van Gogh" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { text: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein" },
  { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { text: "I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'", author: "Muhammad Ali" },
  { text: "It's the repetition of affirmations that leads to belief. And once that belief becomes a deep conviction, things begin to happen.", author: "Muhammad Ali" },
  { text: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Muhammad Ali" },
  { text: "If people aren't laughing at your dreams, your dreams aren't big enough.", author: "Grayson Perry" },
  { text: "Never give up. Today is hard, tomorrow will be worse, but the day after tomorrow will be sunshine.", author: "Jack Ma" },
  { text: "Before you are a leader, success is all about growing yourself. When you become a leader, success is all about growing others.", author: "Jack Welch" },
  { text: "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.", author: "Steve Jobs" },
  { text: "I'm convinced that about half of what separates the successful entrepreneurs from the non-successful ones is pure perseverance.", author: "Steve Jobs" },
  { text: "It’s hardware that makes a machine fast. It’s software that makes a fast machine. It’s discipline that makes a man fast.", author: "Craig Bruce" }
];
